[package]
name = "checksum"
version = "0.2.0"
authors = ["Michael Jochimsen <mlj@troglodytics.org>"]
build = "build.rs"
edition = "2021"

[dependencies]
libc = "0.2"
libz-sys = "1.1"
openssl-sys = "0.9"
